config/routes.rb
Meetmanager::Application.routes.draw do
  filter :small
  resources :events
  resources :athletes
  resources :scores
  resources :teams
  match '/' => 'home#index', :as => :root
  match '/:controller(/:action(/:id))'
#  match 'controllerhome' => '#index', :as => :with_options
end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  self.table_name = "Athlete"
  self.primary_key = "Ath_no"
  default_scope :order => "Last_name, First_name, Initial"

  belongs_to :team, :class_name => "Team", :foreign_key => "Team_no"
  has_many :entries, :class_name => "Entry", :foreign_key => "Ath_no"
  has_many :relay_names, :class_name => "RelayName", :foreign_key => "Ath_no"

  def next(opts = {})
    cond = opts.delete(:conditions)
    id_array = Athlete.select("Ath_no").where(cond)

    id_array.each_index do |i|
      if id_array[i].Ath_no == self.id
	i += 1 if i < id_array.length - 1
	return Athlete.find(id_array[i].Ath_no)
      end
    end
  end

  def previous(opts = {})
    cond = opts.delete(:conditions)
    id_array = Athlete.select("Ath_no").where(cond)

    id_array.each_index do |i|
      if id_array[i].Ath_no == self.id
	i -= 1 if i > 0
	return Athlete.find(id_array[i].Ath_no)
      end
    end
  end

  def middle
    if self.Initial.blank? || self.Initial == '*'
      ''
    else
      self.Initial
    end
  end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_filter :set_team

  def index
    pp = (params && params[:small]) ? 15 : 2000
    @athletes = Athlete.where(cond).paginate(:page => params[:page], :per_page => pp)
  end

  def show
    @athlete = Athlete.find(params[:id])

    if params[:direction]
      case params[:direction]
      when /next/
        a = @athlete.next(:conditions => cond)
	@athlete = a unless a.blank?
      when /previous/
        a = @athlete.previous(:conditions => cond)
	@athlete = a unless a.blank?
      end
    end
    render
  end

  private

  def set_team
    @team = nil

    @team = Team.find(params[:team_id]) if params[:team_id]
  end

  def cond
    { :Team_no => @team.Team_no } if @team
  end
end

app/helpers/athletes_helper.rb
module AthletesHelper
  def combined_name(a)
    a.Last_name.strip + ", " + a.First_name.strip  + (a.middle.strip.length > 0 ? " " + a.middle.strip : "")
  end

  def short_name(a)
    a.Last_name.strip + ", " + a.First_name.strip[0,1] + "."
  end

  def alpha_links(athletes)
    ret = ""
    last_char = ""
    anchors = {}

    athletes.each do |athlete|
      l = athlete.Last_name.upcase[0,1]

      unless last_char == l
	anchors[l] = l
	last_char = l
      end
    end

    ('A' .. 'Z').each do |a|
      ret += (anchors[a] ? '<a href="#' + anchors[a] + '">' : '') + a + (anchors[a] ? '</a>' : '') + '&nbsp;'
    end

    ret.html_safe
  end
end

app/views/athletes/index.html.erb
<h1>
  <%= @team ? @team.Team_name.strip + " - " : "" %>
  Athletes
</h1>

<% if params[:small] -%>
  <%= will_paginate @athletes %>
<% else -%>
  <div style="margin: 20px 0px 0px 0px;"> </div>
  <%= alpha_links(@athletes) %>
  <br />
  <div style="margin: 20px 0px 0px 0px;"> </div>
<% end -%>
<table id="athleteTable">
  <tr>
    <th id="lastName">Last Name</th>
    <th id="firstName">First Name</th>
    <th id="initial">Initial</th>
    <th id="sex">Sex</th>
    <th id="team">Team</th>
    <th id="age">Age</th>
    <th id="prefName">Preferred Name</th>
  </tr>

  <% i = 1
  last_char = ''
  team_param = (@team ? { :team_id => @team.Team_no } : {})
  @athletes.each do |athlete|
    l = athlete.Last_name.upcase[0,1] 
    
    if last_char != '' && last_char != l -%>
</table>
<table id="athleteTable">
 <% end -%>
    <tr class="<%= i % 2 > 0 ? "odd" : "even" %>">
      <%= raw(last_char != l ? '<a name="' + l + '">' : '') %>
      <td id="lastName"><%= link_to athlete.Last_name, athlete_path(athlete, team_param) %></td>
      <%= raw(last_char != l ? '</a>' : '') %>
      <td id="firstName"><%= h athlete.First_name %></td>
      <td id="initial"><%= h athlete.middle %></td>
      <td id="sex"><%= h athlete.Ath_Sex %></td>
      <td id="team"><%= link_to athlete.team.Team_abbr, athletes_path(:team_id => athlete.team) %></td>
      <td id="age" style="text-align: right"><%= h athlete.Ath_age %></td>
      <td id="prefName"><%= h athlete.Pref_name %></td>
    </tr>
  <% last_char = l
    i += 1
  end %>
</table>
<% if params[:small] -%>
  <%= will_paginate @athletes %>
<% end -%>

app/views/athletes/show.html.erb
<% team_param = (@team ? { :team_id => @team.Team_no } : {}) -%>
<h1><%= link_to '<<', athlete_path(@athlete, { :direction => 'previous' }.merge(team_param)) %>
  <%= h @athlete.Last_name %>,&nbsp;<%= h @athlete.First_name %>&nbsp;<%= h @athlete.middle %>
  <%= link_to '>>', athlete_path(@athlete, { :direction => 'next'  }.merge(team_param)) %>
</h1>

<% if @athlete.entries.length > 0 %>
  <h2>Individual Events</h2>

  <table>
    <tr>
      <th>No.</th>
      <th>Event</th>
      <th>Heat</th>
      <th>Lane</th>
      <th>Seed Time</th>
      <th>Time</th>
      <th>Place</th>
      <th>Points</th>
    </tr>
    <% i = 1
    @athlete.entries.sort{ |a, b| a.event.Event_no <=> b.event.Event_no }.each do |entry|
      event = entry.event -%>
      <tr class="<%= i % 2 > 0 ? "odd" : "even" %>">
        <td style="text-align: right"><%= link_to event.Event_no, :controller => 'events', :action => 'results', :id => event %></td>
        <td><%= h event.distance + " " + event.stroke + " " + event.age + " " + event.gender %></td>
        <td style="text-align: right"><%= h entry.Fin_heat %></td>
        <td style="text-align: right"><%= h entry.Fin_lane %></td>
        <td style="text-align: right"><%= h time(entry.ActualSeed_time) %></td>
        <td style="text-align: right"><%= h result_time(entry) %></td>
        <td style="text-align: right"><%= h place(entry.Fin_place) %></td>
        <td style="text-align: right"><%= h score(entry.Ev_score) %></td>
      </tr>
    <% i += 1
    end -%>
  </table>
<% end -%>

<% if @athlete.relay_names.length > 0 %>
  <h2>Relay Events</h2>

  <table>
    <tr>
      <th>No.</th>
      <th>Event</th>
      <th>Heat</th>
      <th>Lane</th>
      <th>Seed Time</th>
      <th>Time</th>
      <th>Place</th>
      <th>Points</th>
    </tr>
    <% i = 1
    @athlete.relay_names.sort{ |a, b| a.relay.event.Event_no <=> b.relay.event.Event_no }.each do |n|
      relay = n.relay
      event = relay.event -%>
      <tr class="<%= i % 2 > 0 ? "odd" : "even" %>">
        <td style="text-align: right"><%= link_to event.Event_no, :controller => 'events', :action => 'results', :id => event %></td>
        <td><%= h event.distance + " " + event.stroke + " " + event.age + " " + event.gender %></td>
        <td style="text-align: right"><%= h relay.Fin_heat %></td>
        <td style="text-align: right"><%= h relay.Fin_lane %></td>
        <td style="text-align: right"><%= h time(relay.ActualSeed_time) %></td>
        <td style="text-align: right"><%= h result_time(relay) %></td>
        <td style="text-align: right"><%= h place(relay.Fin_place) %></td>
        <td style="text-align: right"><%= h score(relay.Ev_score) %></td>
      </tr>
    <% i += 1
    end -%>
  </table>
<% end -%>