config/routes.rb
Meetmanager::Application.routes.draw do
  filter :small
  resources :events
  resources :athletes
  resources :scores
  resources :teams
  match '/' => 'home#index', :as => :root
  match '/:controller(/:action(/:id))'
#  match 'controllerhome' => '#index', :as => :with_options
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>MeetManager: <%= controller.controller_name %> - <%= controller.action_name %></title>
    <%= stylesheet_link_tag 'layout' %>
  </head>
  <body>
    <div id="head">
      <div id="head_left"> </div>
      <div id="head_l2"> </div>
      <div id="head_l3"> </div>
      <div id="head_center">
        <div id="header">
          <div class="h1">Tracy Tritons - Meet Information</div>
          <div class="h2" style="float: left"><%= @meet ? @meet.Meet_name1  : '' %></div>
          <div class="h2" style="float: right">Last Update: <%= @lastrun.strftime("%m/%d/%Y %H:%M") %></div>
          <div style="clear: both"></div>
          <div class="h2" style="float: left"><%= @meet ? @meet.Meet_start.strftime("%m/%d/%Y") : '' %>
            <%= @meet && (@meet.Meet_end > @meet.Meet_start) ? " - " + @meet.Meet_end.strftime("%m/%d/%Y") : "" %>
          </div>
          <div class="h2" style="float: right">Now: <%= Time.now.strftime("%m/%d/%Y %H:%M") %></div>
        </div>
        <div id="logo" style="float: right">
          <%= image_tag 'tt2013_150.jpg', :alt => 'TT team Picture' %>
        </div>
      </div>
      <div id="head_right"> </div>
    </div>
    <div style="clear: both"></div>
    <div id="content">
      <div id="sideBar">
        <%= link_to 'Home', :controller => "home" %><br />
        <%= link_to 'Events', :controller => "events" %><br />
        <%= link_to 'Teams', :controller => "teams" %><br />
        <a href="<%= toggle_small %>"><%= image_tag 'Mobile.gif', :alt => "Layout for Small Screens", :title => "Layout for Small Screens", :style => "margin-top: 150px; border: 0px" %></a>
      </div>
      <div id="pageContent">
        <%= yield %>
      </div>
      <div style="clear: both"></div>
    </div>
    <div id="foot">
      <div id="foot_left"> </div>
      <div id="foot_l2"> </div>
      <div id="foot_l3"> </div>
      <div id="foot_center">
        <div id="footer">
          <p>This information is generated out of snapshots of
            the original meet database.  If there are any discrepencies between
            the information here and the official computer results, the meet
            computer is always correct. Please send questions and comments to
            <a href="mailto:marco@sonic.net">Marco Walther</a>
          </p>
        </div>
      </div>
      <div id="foot_right"> </div>
    </div>
  </body>
</html>

app/views/layouts/small.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>MeetManager: <%= controller.controller_name %> - <%= controller.action_name %></title>
    <%= stylesheet_link_tag 'small_layout' %>
  </head>
  <body>
    <div id="head">
      <div id="header">
        <div class="h2" style="float: left"><%= @meet ? @meet.Meet_name1  : '' %></div>
        <div class="h2" style="float: right">Last Update: <%= @lastrun.strftime("%m/%d/%Y %H:%M") %></div>
        <div style="clear: both"></div>
        <div class="h2" style="float: left"><%= @meet ? @meet.Meet_start.strftime("%m/%d/%Y") : '' %>
          <%= @meet && (@meet.Meet_end > @meet.Meet_start) ? " - " + @meet.Meet_end.strftime("%m/%d/%Y") : "" %>
        </div>
        <div class="h2" style="float: right">Now: <%= Time.now.strftime("%m/%d/%Y %H:%M") %></div>
        <div style="clear: both"></div>
        <div id="headNav">
          <%= link_to 'Home', root_path %>
          <%= link_to 'Events', events_path(:stroke => Event.strokes[0][:stroke], :relay => Event.strokes[0][:relay], :long => Event.strokes[0][:long]) %>
          <%= link_to 'Teams', teams_path %>
        </div>
      </div>
    </div>
    <div style="clear: both"></div>
    <div id="content">
      <%= yield %>
      <div style="clear: both"></div>
    </div>
    <div id="foot">
      <div id="footer">
        The meet computer is always correct.
        <div  style="float: right">
          <a href="<%= toggle_small() %>">Large</a>
        </div>
      </div>
    </div>
  </body>
</html>